language: objective-c
osx_image: xcode10

notifications:
  email: false
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.4.1
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  - xcodebuild -project Example/Example.xcodeproj -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
