language: swift
osx_image: xcode10.2
notifications:
  email: false

before_install:
  - brew update
  - gem install bundler
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -project Example/Example.xcodeproj -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
